[phases.setup]
nixPkgs = ["ffmpeg", "yt-dlp"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2"
